// src/styles/dashboardStyles.js
import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#0d1117",
  panel: "rgba(255,255,255,0.02)",
  text: "#e8e8ea",
  muted: "#9aa3ad",
  blue: "#1e90ff",
  mint: "#00f0a8",
  green: "#32cd32",
  glow: "#00f0a8",
  accent: "#00c7a7",
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  safeArea: { flex: 1, backgroundColor: COLORS.bg },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  brand: { color: COLORS.text, fontSize: 22, fontWeight: "800" },
  searchInput: {
    flex: 1,
    marginHorizontal: 12,
    backgroundColor: "#0b0c0f",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    color: COLORS.text,
  },
  containerPadding: { paddingHorizontal: 12, paddingBottom: 20 },
  analyticsCard: {
    marginTop: 10,
    borderRadius: 12,
    padding: 12,
    backgroundColor: COLORS.panel,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  cardsRow: { flexDirection: "row", gap: 12, justifyContent: "space-between" },
  metric: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.01)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  metricValue: { color: COLORS.blue, fontWeight: "800", fontSize: 16 },
  metricLabel: { color: COLORS.muted, fontSize: 12 },
  composerCard: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: COLORS.panel,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  composeText: {
    minHeight: 64,
    color: COLORS.text,
    backgroundColor: "transparent",
    fontSize: 14,
    padding: 8,
  },
  feedList: { paddingTop: 14 },
  fab: {
    position: "absolute",
    right: 18,
    bottom: 26,
    width: 58,
    height: 58,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: COLORS.mint,
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  glass: {
    backgroundColor: COLORS.panel,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  sidebarDrawer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 300,
    backgroundColor: COLORS.bg,
    padding: 16,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.02)",
  },
  smallMuted: { color: COLORS.muted, fontSize: 12 },
});